services:
  - type: web
    name: yt-knowledge-assistant
    runtime: python
    buildCommand: ./build.sh
    startCommand: "export PATH=$PWD/node-v20.11.0-linux-x64/bin:$PWD/ffmpeg:$PATH && uvicorn backend.app:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: GROQ_API_KEY
        sync: false
